// Code generated by mockery v2.12.2. DO NOT EDIT.

package alerter

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockAlert is an autogenerated mock type for the Alert type
type MockAlert struct {
	mock.Mock
}

// Message provides a mock function with given fields:
func (_m *MockAlert) Message() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ShouldIgnoreResource provides a mock function with given fields:
func (_m *MockAlert) ShouldIgnoreResource() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockAlert creates a new instance of MockAlert. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAlert(t testing.TB) *MockAlert {
	mock := &MockAlert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
