// Code generated by mockery v2.12.2. DO NOT EDIT.

package terraform

import (
	mock "github.com/stretchr/testify/mock"
	cty "github.com/zclconf/go-cty/cty"

	testing "testing"
)

// MockResourceReader is an autogenerated mock type for the ResourceReader type
type MockResourceReader struct {
	mock.Mock
}

// ReadResource provides a mock function with given fields: args
func (_m *MockResourceReader) ReadResource(args ReadResourceArgs) (*cty.Value, error) {
	ret := _m.Called(args)

	var r0 *cty.Value
	if rf, ok := ret.Get(0).(func(ReadResourceArgs) *cty.Value); ok {
		r0 = rf(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cty.Value)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(ReadResourceArgs) error); ok {
		r1 = rf(args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockResourceReader creates a new instance of MockResourceReader. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResourceReader(t testing.TB) *MockResourceReader {
	mock := &MockResourceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
