// Code generated by mockery v2.12.2. DO NOT EDIT.

package terraform

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockProviderDownloaderInterface is an autogenerated mock type for the ProviderDownloaderInterface type
type MockProviderDownloaderInterface struct {
	mock.Mock
}

// Download provides a mock function with given fields: url, path
func (_m *MockProviderDownloaderInterface) Download(url string, path string) error {
	ret := _m.Called(url, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProviderDownloaderInterface creates a new instance of MockProviderDownloaderInterface. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProviderDownloaderInterface(t testing.TB) *MockProviderDownloaderInterface {
	mock := &MockProviderDownloaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
