// Code generated by mockery v2.12.2. DO NOT EDIT.

package terraform

import (
	providers "github.com/hashicorp/terraform/providers"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockSchemaSupplier is an autogenerated mock type for the SchemaSupplier type
type MockSchemaSupplier struct {
	mock.Mock
}

// Schema provides a mock function with given fields:
func (_m *MockSchemaSupplier) Schema() map[string]providers.Schema {
	ret := _m.Called()

	var r0 map[string]providers.Schema
	if rf, ok := ret.Get(0).(func() map[string]providers.Schema); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]providers.Schema)
		}
	}

	return r0
}

// NewMockSchemaSupplier creates a new instance of MockSchemaSupplier. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSchemaSupplier(t testing.TB) *MockSchemaSupplier {
	mock := &MockSchemaSupplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
