// Code generated by mockery v2.12.2. DO NOT EDIT.

package terraform

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockHomeDirInterface is an autogenerated mock type for the HomeDirInterface type
type MockHomeDirInterface struct {
	mock.Mock
}

// Dir provides a mock function with given fields:
func (_m *MockHomeDirInterface) Dir() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHomeDirInterface creates a new instance of MockHomeDirInterface. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHomeDirInterface(t testing.TB) *MockHomeDirInterface {
	mock := &MockHomeDirInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
