// Code generated by mockery v2.12.2. DO NOT EDIT.

package enumerator

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockStateEnumerator is an autogenerated mock type for the StateEnumerator type
type MockStateEnumerator struct {
	mock.Mock
}

// Enumerate provides a mock function with given fields:
func (_m *MockStateEnumerator) Enumerate() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Origin provides a mock function with given fields:
func (_m *MockStateEnumerator) Origin() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockStateEnumerator creates a new instance of MockStateEnumerator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStateEnumerator(t testing.TB) *MockStateEnumerator {
	mock := &MockStateEnumerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
