// Code generated by mockery v2.12.2. DO NOT EDIT.

package output

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockPrinter is an autogenerated mock type for the Printer type
type MockPrinter struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, args
func (_m *MockPrinter) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewMockPrinter creates a new instance of MockPrinter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPrinter(t testing.TB) *MockPrinter {
	mock := &MockPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
