// Code generated by mockery v2.12.2. DO NOT EDIT.

package output

import (
	analyser "github.com/snyk/driftctl/pkg/analyser"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockOutput is an autogenerated mock type for the Output type
type MockOutput struct {
	mock.Mock
}

// Write provides a mock function with given fields: analysis
func (_m *MockOutput) Write(analysis *analyser.Analysis) error {
	ret := _m.Called(analysis)

	var r0 error
	if rf, ok := ret.Get(0).(func(*analyser.Analysis) error); ok {
		r0 = rf(analysis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOutput creates a new instance of MockOutput. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOutput(t testing.TB) *MockOutput {
	mock := &MockOutput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
