// Code generated by mockery v2.12.2. DO NOT EDIT.

package resource

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockNormalizedResource is an autogenerated mock type for the NormalizedResource type
type MockNormalizedResource struct {
	mock.Mock
}

// NormalizeForProvider provides a mock function with given fields:
func (_m *MockNormalizedResource) NormalizeForProvider() (Resource, error) {
	ret := _m.Called()

	var r0 Resource
	if rf, ok := ret.Get(0).(func() Resource); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Resource)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NormalizeForState provides a mock function with given fields:
func (_m *MockNormalizedResource) NormalizeForState() (Resource, error) {
	ret := _m.Called()

	var r0 Resource
	if rf, ok := ret.Get(0).(func() Resource); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Resource)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNormalizedResource creates a new instance of MockNormalizedResource. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNormalizedResource(t testing.TB) *MockNormalizedResource {
	mock := &MockNormalizedResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
