// Code generated by mockery v2.12.2. DO NOT EDIT.

package resource

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockResourceFactory is an autogenerated mock type for the ResourceFactory type
type MockResourceFactory struct {
	mock.Mock
}

// CreateAbstractResource provides a mock function with given fields: ty, id, data
func (_m *MockResourceFactory) CreateAbstractResource(ty string, id string, data map[string]interface{}) *Resource {
	ret := _m.Called(ty, id, data)

	var r0 *Resource
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) *Resource); ok {
		r0 = rf(ty, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Resource)
		}
	}

	return r0
}

// NewMockResourceFactory creates a new instance of MockResourceFactory. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResourceFactory(t testing.TB) *MockResourceFactory {
	mock := &MockResourceFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
