// Code generated by mockery v2.12.2. DO NOT EDIT.

package error

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockRemoteError is an autogenerated mock type for the RemoteError type
type MockRemoteError struct {
	mock.Mock
}

// ListedTypeError provides a mock function with given fields:
func (_m *MockRemoteError) ListedTypeError() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockRemoteError creates a new instance of MockRemoteError. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRemoteError(t testing.TB) *MockRemoteError {
	mock := &MockRemoteError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
