// Code generated by mockery v2.12.2. DO NOT EDIT.

package repository

import (
	cloudformation "github.com/aws/aws-sdk-go/service/cloudformation"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockCloudformationRepository is an autogenerated mock type for the CloudformationRepository type
type MockCloudformationRepository struct {
	mock.Mock
}

// ListAllStacks provides a mock function with given fields:
func (_m *MockCloudformationRepository) ListAllStacks() ([]*cloudformation.Stack, error) {
	ret := _m.Called()

	var r0 []*cloudformation.Stack
	if rf, ok := ret.Get(0).(func() []*cloudformation.Stack); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*cloudformation.Stack)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCloudformationRepository creates a new instance of MockCloudformationRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCloudformationRepository(t testing.TB) *MockCloudformationRepository {
	mock := &MockCloudformationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
