// Code generated by mockery v2.12.2. DO NOT EDIT.

package repository

import (
	armcontainerregistry "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockContainerRegistryRepository is an autogenerated mock type for the ContainerRegistryRepository type
type MockContainerRegistryRepository struct {
	mock.Mock
}

// ListAllContainerRegistries provides a mock function with given fields:
func (_m *MockContainerRegistryRepository) ListAllContainerRegistries() ([]*armcontainerregistry.Registry, error) {
	ret := _m.Called()

	var r0 []*armcontainerregistry.Registry
	if rf, ok := ret.Get(0).(func() []*armcontainerregistry.Registry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*armcontainerregistry.Registry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockContainerRegistryRepository creates a new instance of MockContainerRegistryRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockContainerRegistryRepository(t testing.TB) *MockContainerRegistryRepository {
	mock := &MockContainerRegistryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
