// Code generated by mockery v2.12.2. DO NOT EDIT.

package repository

import (
	armnetwork "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// mockNetworkSecurityGroupsClient is an autogenerated mock type for the networkSecurityGroupsClient type
type mockNetworkSecurityGroupsClient struct {
	mock.Mock
}

// ListAll provides a mock function with given fields: options
func (_m *mockNetworkSecurityGroupsClient) ListAll(options *armnetwork.NetworkSecurityGroupsListAllOptions) networkSecurityGroupsListAllPager {
	ret := _m.Called(options)

	var r0 networkSecurityGroupsListAllPager
	if rf, ok := ret.Get(0).(func(*armnetwork.NetworkSecurityGroupsListAllOptions) networkSecurityGroupsListAllPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(networkSecurityGroupsListAllPager)
		}
	}

	return r0
}

// newMockNetworkSecurityGroupsClient creates a new instance of mockNetworkSecurityGroupsClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNetworkSecurityGroupsClient(t testing.TB) *mockNetworkSecurityGroupsClient {
	mock := &mockNetworkSecurityGroupsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
