// Code generated by mockery v2.12.2. DO NOT EDIT.

package repository

import (
	armresources "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// mockResourcesClient is an autogenerated mock type for the resourcesClient type
type mockResourcesClient struct {
	mock.Mock
}

// List provides a mock function with given fields: options
func (_m *mockResourcesClient) List(options *armresources.ResourceGroupsListOptions) resourcesListPager {
	ret := _m.Called(options)

	var r0 resourcesListPager
	if rf, ok := ret.Get(0).(func(*armresources.ResourceGroupsListOptions) resourcesListPager); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resourcesListPager)
		}
	}

	return r0
}

// newMockResourcesClient creates a new instance of mockResourcesClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newMockResourcesClient(t testing.TB) *mockResourcesClient {
	mock := &mockResourcesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
